services:
  - docker

before_install:
- docker build ./test -t krpc.js/krpc.js

before_script:
- docker run -p 50000:50000 -p 50001:50001 --rm krpc.js/krpc.js
- until curl 172.17.0.1:50000; do sleep 1; done

script:
- npm run test
